[package]
name = "uon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uon_lib = { version = "0.1.0", path = "uon_lib" }
